import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const dashboardStyles = StyleSheet.create({
  scrollContent: {
    padding: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  greetingText: {
    fontSize: theme.typography.sizes.lg + 2,
    fontWeight: '600',
    color: theme.colors.text.primary,
    letterSpacing: -0.5,
  },
  greetingSubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    fontWeight: '400',
    marginTop: 4,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  section: {
    marginBottom: theme.spacing.xl,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.text.secondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  subjectsRow: {
    gap: 16,
    paddingVertical: 4,
  },
  subjectsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  subjectsAddBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectsCarousel: {
    paddingVertical: 4,
    paddingRight: 4,
  },
  subjectTile: {
    width: 208,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  subjectBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    zIndex: 2,
  },
  subjectTileName: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  subjectTileMeta: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.text.secondary,
    marginTop: 2,
  },
  subjectTileStats: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    marginTop: 6,
    fontWeight: '600',
  },
  emptySubjectsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
  },
  emptySubjectsText: {
    color: theme.colors.text.secondary,
    fontSize: theme.typography.sizes.sm,
  },
  subjectCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  subjectImage: {
    width: '100%',
    height: '100%',
  },
  quickAddCard: {
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAddTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  quickAddDesc: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.text.secondary,
    marginBottom: 16,
  },
  quickAddBtn: {
    backgroundColor: theme.colors.white,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAddBtnText: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  nextClassCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.lg,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  nextClassInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  nextClassBadge: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: theme.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextClassTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  nextClassRoom: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.text.secondary,
    marginTop: 2,
  },
  openBtn: {
    backgroundColor: theme.colors.inputBackground,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: theme.borderRadius.full,
  },
  openBtnText: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  grid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '600',
    flex: 1,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardValue: {
    fontSize: 24,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  cardSubtext: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 20,
  },
  actionItem: {
    width: '45%',
    alignItems: 'center',
  },
  actionCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    ...globalStyles.shadow,
  },
  actionText: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '500',
    color: theme.colors.text.secondary,
  },
  allChip: {
    backgroundColor: '#C7C7CC',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: theme.borderRadius.full,
  },
  allChipText: {
    color: theme.colors.white,
    fontWeight: '600',
    fontSize: 12,
  },
  perfContainer: {
    gap: 12,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-end',
  },
  sheetContent: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: theme.spacing.xl,
    paddingBottom: theme.spacing.xl + 10,
    maxHeight: '85%',
    ...globalStyles.shadow,
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.colors.text.primary,
    letterSpacing: -0.5,
  },
  sheetSubtitle: {
    marginTop: 4,
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginBottom: 14,
  },
  sheetLabel: {
    marginTop: 8,
    marginBottom: 6,
    fontSize: theme.typography.sizes.sm,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  sheetInput: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.colors.text.primary,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  colorOption: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  colorOptionSelected: {
    borderWidth: 2,
    borderColor: theme.colors.text.primary,
  },
  iconOption: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.inputBackground,
  },
  iconOptionSelected: {
    borderColor: theme.colors.primary,
    borderWidth: 2,
  },
  sheetActions: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetCancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.full,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
  },
  sheetCancelText: {
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  sheetSaveBtn: {
    flex: 1,
    borderRadius: theme.borderRadius.full,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
  },
  sheetSaveText: {
    color: theme.colors.white,
    fontWeight: '600',
  },
  perfRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.lg,
  },
  perfRowYou: {
    backgroundColor: theme.colors.background,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  perfRank: {
    width: 40,
    fontWeight: '600',
    color: theme.colors.text.secondary,
  },
  perfUser: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  perfName: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.primary,
  },
  perfGpa: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '600',
    color: theme.colors.text.secondary,
  },
  quickAddMenuContainer: {
    marginTop: 20,
    gap: 16,
  },
  quickAddMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  quickAddMenuIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  quickAddMenuInfo: {
    flex: 1,
  },
  quickAddMenuText: {
    fontSize: 15,
    fontWeight: '500',
    color: theme.colors.text.primary,
  },
  quickAddMenuSubtext: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    marginTop: 1,
    fontWeight: '400',
  },
  quickAddMenuChevron: {
    opacity: 0.3,
  },
  // DROPDOWN / PICKER REPLACEMENT
  dropdownSelector: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
  },
  dropdownSelectorText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.primary,
  },
  dropdownPlaceholder: {
    color: theme.colors.text.placeholder,
  },
  // TOAST STYLE (Simple)
  toastContainer: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: theme.borderRadius.full,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...globalStyles.shadow,
    zIndex: 999,
  },
  toastText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: theme.typography.sizes.sm,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...globalStyles.shadow,
    elevation: 8,
    zIndex: 900,
  },
  gridContainer: {
    height: 460,
    backgroundColor: theme.colors.background,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 10,
  },
  gridHeader: {
    flexDirection: 'row',
    backgroundColor: theme.colors.inputBackground,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  hourColHeader: {
    width: 50,
  },
  dayColHeader: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border + '40',
  },
  dayHeaderText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
  },
  scheduleHintText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    marginBottom: 10,
  },
  gridRow: {
    flexDirection: 'row',
    height: 44,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '40',
  },
  hourCol: {
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground + '50',
  },
  hourText: {
    fontSize: 10,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  gridCell: {
    flex: 1,
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  slotIndicator: {
    width: '80%',
    height: '80%',
    borderRadius: 4,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
});
