import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const subjectsStyles = StyleSheet.create({
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.xl, paddingVertical: theme.spacing.md,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border,
  },
  headerTitle: { fontSize: theme.typography.sizes.lg, fontWeight: '800', color: theme.colors.text.primary },
  addBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: theme.colors.text.primary,
    justifyContent: 'center', alignItems: 'center',
  },
  searchRow: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: theme.spacing.xl, paddingVertical: theme.spacing.sm,
  },
  searchBox: {
    flex: 1, flexDirection: 'row', alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.md, height: 40,
  },
  searchInput: { flex: 1, fontSize: theme.typography.sizes.sm, color: theme.colors.text.primary },
  filterBtn: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  scroll: { padding: theme.spacing.xl, paddingBottom: 40 },
  section: { marginBottom: theme.spacing.xl },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  sectionHint: { fontSize: 11, color: theme.colors.text.secondary },
  subjectCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.md,
    marginBottom: 16, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  subjectCardSelected: { borderColor: theme.colors.primary, borderWidth: 1.5 },
  subjectTop: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  codeCircle: {
    width: 44, height: 44, borderRadius: 22,
    justifyContent: 'center', alignItems: 'center',
  },
  codeText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  subjectName: { fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.primary },
  subjectProf: { fontSize: 11, color: theme.colors.text.secondary },
  creditsText: { fontSize: 11, color: theme.colors.text.secondary, fontWeight: '600' },
  avgText: { fontSize: theme.typography.sizes.sm, fontWeight: '700' },
  progressBar: {
    height: 6, backgroundColor: theme.colors.inputBackground,
    borderRadius: 3, marginBottom: 10, overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 3 },
  subjectBottom: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  assessmentBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  assessmentBtnText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  iconAction: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  nextLabel: { flex: 1, fontSize: 10, color: theme.colors.text.secondary, textAlign: 'right' },
  // ── Calculator ──
  calcCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    marginBottom: theme.spacing.xl, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  calcHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  calcTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary, flex: 1 },
  calcSubject: { fontSize: 11, color: theme.colors.primary, fontWeight: '600', textAlign: 'right', flex: 1 },
  calcInputsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  calcInputBox: { flex: 1, alignItems: 'center' },
  calcInputLabel: { fontSize: 10, color: theme.colors.text.secondary, marginBottom: 4, textAlign: 'center' },
  calcInput: {
    width: '100%', textAlign: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: theme.colors.border,
    padding: 8, fontSize: theme.typography.sizes.md, fontWeight: '700',
    color: theme.colors.text.primary,
  },
  calcHint: { fontSize: 11, color: theme.colors.text.secondary, marginBottom: 8 },
  calcResult: { fontSize: 40, fontWeight: '900', textAlign: 'center', marginBottom: 4 },
  calcStatus: { fontSize: theme.typography.sizes.sm, fontWeight: '700', textAlign: 'center', marginBottom: 12 },
  statusBar: { flexDirection: 'row', height: 8, marginBottom: 6, borderRadius: 4, overflow: 'hidden' },
  statusSegment: { flex: 1 },
  statusLegend: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 16 },
  legendText: { fontSize: 11, fontWeight: '600' },
  calcActions: { flexDirection: 'row', gap: 8 },
  calcBtn: {
    flex: 1, backgroundColor: theme.colors.text.primary,
    paddingVertical: 10, borderRadius: theme.borderRadius.full, alignItems: 'center',
  },
  calcBtnText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  calcBtnSecondary: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border },
  calcBtnReset: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 14, borderRadius: theme.borderRadius.full, justifyContent: 'center' },
  calcBtnSecText: { color: theme.colors.text.primary, fontWeight: '600', fontSize: 11 },
  // ── Assessments ──
  assessCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  assessHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  assessTitle: { fontSize: theme.typography.sizes.sm, fontWeight: '800', color: theme.colors.text.primary, flex: 1 },
  addAssessBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 5, borderRadius: theme.borderRadius.full,
  },
  addAssessBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  assessRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: theme.colors.border,
  },
  assessIconBox: {
    width: 40, height: 40, borderRadius: 12,
    justifyContent: 'center', alignItems: 'center',
  },
  assessName: { fontSize: theme.typography.sizes.sm, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 2 },
  assessMeta: { fontSize: 11, color: theme.colors.text.secondary },
  assessScore: { fontSize: 12, fontWeight: '700', color: theme.colors.text.primary, marginBottom: 2 },
  editText: { fontSize: 11, color: theme.colors.primary, fontWeight: '600' },
  sparklineContainer: { paddingTop: 16, marginBottom: 12 },
  sparklineLabel: { fontSize: 11, color: theme.colors.text.secondary, marginBottom: 8 },
  sparkline: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, height: 50 },
  sparkBar: { flex: 1, borderRadius: 3 },
  photoRow: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border,
  },
  photoText: { flex: 1, fontSize: 11, color: theme.colors.text.secondary },
  photoBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  photoBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
});
